[[0.82027938]
 [0.97438708]
 [0.11202629]
 [0.37646924]
 [0.55391159]
 [0.41293132]
 [0.49300659]
 [0.96275433]
 [0.08786818]
 [0.34947497]]
0.514310898023387


In [3]:
array1=np.random.random(size=(20,1))
print(array1)
var=array1.var()
std=array1.std()
print(var)
print(std)

[[0.97598496]
 [0.54964138]
 [0.29549956]
 [0.64779528]
 [0.34629607]
 [0.03368468]
 [0.3482323 ]
 [0.09342823]
 [0.7027601 ]
 [0.813954  ]
 [0.0165539 ]
 [0.2146278 ]
 [0.24878988]
 [0.97217659]
 [0.59346358]
 [0.28133543]
 [0.13118434]
 [0.51341232]
 [0.97259057]
 [0.27721247]]
0.09407721065566757
0.30672008518463145


In [4]:
arr=np.random.random(size=(10,20))
arr1=np.random.random(size=(20,25))
arr2=np.matmul(arr,arr1)
print(arr2)
arr2.sum()

[[4.93184185 4.52457008 4.54477739 4.60398764 4.8707801  3.75936873
  4.00277789 4.71592854 4.63227115 4.04784757 3.79969031 4.21170776
  4.40989102 3.96332953 4.78330812 3.27546283 4.27120763 4.38065953
  3.48880366 4.50033305 4.30154454 4.811724   3.85959704 4.76919417
  4.97919249]
 [4.98767852 4.72132692 5.34255611 6.58598773 6.25451512 5.60349833
  5.29947136 4.75251462 5.41537051 4.62900678 5.06077371 5.44047212
  5.03137269 4.80902938 4.69467178 4.20863458 4.97867929 4.97167283
  4.13769617 4.79323439 4.66770549 5.25656755 4.77481163 5.12969249
  4.5037608 ]
 [4.64535923 4.32142793 4.87559716 4.42448857 4.30656191 3.19573776
  4.17681913 3.72539254 3.86092622 3.64252635 3.57932626 3.52084541
  4.59640583 3.7026298  3.70846842 3.77428378 4.53672534 3.56515173
  3.35060602 3.16142833 3.62712409 3.54828223 3.00632997 3.7921396
  4.26228485]
 [5.24085305 5.30504022 5.65300351 5.90218496 5.49036967 5.43433271
  4.46114314 4.42614919 4.77238578 4.68561074 5.62919695 4.93332354
  5.524

1227.588313037537

In [5]:
array2=np.random.random(size=(10,1))
print(array2)
print("*"*80)
array3=np.ndarray((10,1))
def func(x):
    return 1/1+ np.exp(-x)
List=list()
List1=list()
for i in range(0,array2.shape[0]):
    List.clear()
    for j in array2[i]:
        List.append(func(j))
    List1.append(List)
print(List1)
np.array(List1)

[[0.85303791]
 [0.06356593]
 [0.69515187]
 [0.32127915]
 [0.70402724]
 [0.97909988]
 [0.79796528]
 [0.86853064]
 [0.20132552]
 [0.2503144 ]]
********************************************************************************
[[1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487], [1.7785559703205487]]


array([[1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597],
       [1.77855597]])